[project]
name = "python-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.0",
    "ruff>=0.11.13",
    "ty>=0.0.1a10",
]
